# ABOUT: converting web scraped data to a Pandas dataframe

import pandas as pd
from Injury import rows # list of strings containing scraped data

location = {
    "Rio de Janeiro ATP Singles": "Rio de Janeiro",
    "Doha ATP Singles": "Doha",
    "Marseille ATP Singles": "Marseille",
    "Monterrey Ch Singles": "Monterrey",
    "Bengaluru Ch Singles": "Bengaluru",
    "Rome GA Ch Singles Q": "Rome",
    "Rome GA Ch Singles": "Rome",
    "Rovereto Ch Singles Q": "Rovereto",
    "Rovereto Ch Singles": "Rovereto",
    "Dubai WTA Singles": "Dubai",
    "Merida WTA Singles": "Merida",
    "Rotterdam ATP Singles": "Rotterdam",
    "Delray Beach ATP Singles Q": "Delray Beach",
    "Delray Beach ATP Singles": "Delray Beach",
    "Manama Ch Singles": "Manama",
    "Chennai Ch Singles Q": "Chennai",
    "Chennai Ch Singles": "Chennai",
    "Cherbourg Ch Singles Q": "Cherbourg",
    "Doha WTA Singles": "Doha",
    "Doha WTA Singles Q": "Doha",
    "Dallas ATP Singles Q": "Dallas",
    "Dallas ATP Singles": "Dallas",
    "Cordoba ATP Singles Q": "Cordoba",
    "Cordoba ATP Singles": "Cordoba",
    "Montpellier ATP Singles Q": "Montpellier",
    "Montpellier ATP Singles": "Montpellier",
    "Vilnius Ch Singles": "Vilnius",
    "Tenerife Ch Singles Q": "Tenerife",
    "Tenerife Ch Singles": "Tenerife",
    "Abu Dhabi WTA Singles Q": "Abu Dhabi",
    "Abu Dhabi WTA Singles": "Abu Dhabi",
    "Linz WTA Singles": "Linz",
    "Koblenz Ch Singles Q": "Koblenz",
    "Koblenz Ch Singles": "Koblenz",
    "Burnie Ch Singles Q": "Burnie",
    "Cleveland Ch Singles Q": "Cleveland",
    "Lyon WTA Singles": "Lyon",
    "Hua Hin WTA Singles Q": "Hua Hin",
    "Hua Hin WTA Singles": "Hua Hin",
    "Concepcion Ch Singles": "Concepcion",
    "Ottignies-Louvain-La-Neuve Ch Singles Q": "Ottignies-Louvain-La-Neuve",
    "Quimper Ch Singles Q": "Quimper",
    "Quimper Ch Singles": "Quimper",
    "Piracicaba Ch Singles Q": "Piracicaba",
    "Piracicaba Ch Singles": "Piracicaba",
    "Nonthaburi 3 Ch Singles Q": "Nonthaburi",
    "Nonthaburi 3 Ch Singles": "Nonthaburi",
    "Auckland ATP Singles": "Auckland",
    "Adelaide ATP Singles Q": "Adelaide",
    "Adelaide ATP Singles": "Adelaide",
    "Adelaide WTA Singles": "Adelaide",
    "Hobart WTA Singles Q": "Hobart",
    "Hobart WTA Singles": "Hobart",
    "Nonthaburi 2 Singles Q": "Nonthaburi",
    "Oeiras 2 Ch Singles": "Oeiras",
    "Tigre 2 Ch Singles Q": "Tigre",
    "Tigre 2 Ch Singles": "Tigre",
    "Pune ATP Singles Q": "Pune",
    "Pune ATP Singles": "Pune",
    "Adelaide WTA Singles Q": "Adelaide",
    "Auckland WTA Singles": "Auckland",
    "Auckland WTA Singles Q": "Auckland",
    "Noumea Ch Singles": "Noumea",
    "Tigre 1 Ch Singles Q": "Tigre",
    "Tigre 1 Ch Singles": "Tigre",
    "Oeiras 1 Ch Singles": "Oeiras",
    "Roanne Ch Singles": "Roanne",
    "Bratislava Ch Singles": "Bratislava",
    "Knoxville Ch Singles Q": "Knoxville",
    "Matsuyama Ch Singles Q": "Matsuyama",
    "Matsuyama Ch Singles": "Matsuyama",
    "Montevideo Ch Singles": "Montevideo",
    "Paris TMS Singles": "Paris",
    "Guayaquil Ch Singles Q": "Guayaquil",
    "Guayaquil Ch Singles": "Guayaquil",
    "Sydney Ch Singles": "Sydney",
    "Yokohama Ch Singles Q": "Yokohama",
    "Yokohama Ch Singles": "Yokohama",
    "Bergamo Ch Singles Q": "Bergamo",
    "Bergamo Ch Singles": "Bergamo",
    "Midland WTA Singles": "Midland",
    "Vienna ATP Singles": "Vienna",
    "Basel ATP Singles": "Basel",
    "Brest Ch Singles": "Brest",
    "Playford Ch Singles Q": "Playford",
    "Las Vegas Ch Singles Q": "Las Vegas",
    "Las Vegas Ch Singles": "Las Vegas",
    "Lima Ch Singles Q": "Lima",
    "Lima Ch Singles": "Lima",
    "Ortisei Ch Singles Q": "Ortisei",
    "Ortisei Ch Singles": "Ortisei",
    "Tampico WTA Singles Q": "Tampico",
    "Antwerp ATP Singles Q": "Antwerp",
    "Antwerp ATP Singles": "Antwerp",
    "Stockholm ATP Singles Q": "Stockholm",
    "Busan Ch Singles Q": "Busan",
    "Busan Ch Singles": "Busan",
    "Hamburg Ch Singles": "Hamburg",
    "Naples ATP Singles Q": "Naples",
    "Naples ATP Singles": "Naples",
    "Guadalajara WTA Singles": "Guadalajara",
    "Rouen WTA Singles": "Rouen",
    "Gijon ATP Singles": "Gijon",
    "Gijon ATP Singles Q": "Gijon",
    "Florence ATP Singles": "Florence",
    "Seoul Ch Singles": "Seoul",
    "St. Tropez Ch Singles Q": "St. Tropez",
    "St. Tropez Ch Singles": "St. Tropez",
    "Ismaning Ch Singles": "Ismaning",
    "San Diego WTA Singles": "San Diego",
    "San Diego WTA Singles Q": "San Diego",
    "Cluj-Napoca WTA Singles Q": "Cluj-Napoca",
    "Cluj-Napoca WTA Singles": "Cluj-Napoca",
    "Astana ATP Singles": "Astana",
    "Tokyo ATP Singles": "Tokyo",
    "Parma Ch Singles": "Parma",
    "Mouilleron Le Captif Ch Singles": "Mouilleron Le Captif",
    "Campinas Ch Singles": "Campinas",
    "Campinas Ch Singles Q": "Campinas",
    "Gwangju Ch Singles": "Gwangju",
    "Gwangju Ch Singles Q": "Gwangju",
    "Tiburon Ch Singles": "Tiburon",
    "Alicante Ch Singles Q": "Alicante",
    "Alicante Ch Singles": "Alicante",
    "Monastir WTA Singles Q": "Monastir",
    "Monastir WTA Singles": "Monastir",
    "Ostrava WTA Singles Q": "Ostrava",
    "Ostrava WTA Singles": "Ostrava",
    "Seoul ATP Singles": "Seoul",
    "Tel Aviv ATP Singles": "Tel Aviv",
    "Sofia ATP Singles": "Sofia",
    "Sofia ATP Singles Q": "Sofia",
    "Orleans Ch Singles": "Orleans",
    "Lisbon Ch Singles Q": "Lisbon",
    "Lisbon Ch Singles": "Lisbon",
    "Buenos Aires Ch Singles Q": "Buenos Aires",
    "Buenos Aires Ch Singles": "Buenos Aires",
    "Charleston Ch Singles": "Charleston",
    "Parma WTA Singles": "Parma",
    "Tallinn WTA Singles": "Tallinn",
    "Metz ATP Singles": "Metz",
    "San Diego ATP Singles": "San Diego",
    "Genoa Ch Singles": "Genoa",
    "Braga Ch Singles": "Braga",
    "Braga Ch Singles Q": "Braga",
    "Villa Maria Ch Singles": "Villa Maria",
    "Sibiu Ch Singles": "Sibiu",
    "Columbus Ch Singles": "Columbus",
    "Tokyo WTA Singles": "Tokyo",
    "Budapest WTA Singles": "Budapest",
    "Szczecin Ch Singles Q": "Szczecin",
    "Cary Ch Singles": "Cary",
    "Istanbul Ch Singles": "Istanbul",
    "Bucharest WTA Singles": "Bucharest",
    "Portoroz WTA Singles": "Portoroz",
    "Tulln Ch Singles": "Tulln",
    "Seville Ch Singles": "Seville",
    "Cassis Ch Singles Q": "Cassis",
    "Nonthaburi Ch Singles Q": "Nonthaburi",
    "Nonthaburi Ch Singles": "Nonthaburi",
    "Como Ch Singles Q": "Como",
    "Como Ch Singles": "Como",
    "Toulouse Ch Singles Q": "Toulouse",
    "Toulouse Ch Singles": "Toulouse",
    "Mallorca Ch Singles Q": "Mallorca",
    "Mallorca Ch Singles": "Mallorca",
    "Winston-Salem ATP Singles": "Winston-Salem",
    "Banja Luka Ch Singles Q": "Banja Luka",
    "Banja Luka Ch Singles": "Banja Luka",
    "Prague Ch Singles Q": "Prague",
    "Prague Ch Singles": "Prague",
    "Cleveland WTA Singles": "Cleveland",
    "Granby WTA Singles Q": "Granby",
    "Granby WTA Singles": "Granby",
    "Cincinnati TMS Singles Q": "Cincinnati",
    "Cincinnati TMS Singles": "Cincinnati",
    "Vancouver Ch Singles Q": "Vancouver",
    "Vancouver Ch Singles": "Vancouver",
    "Santo Domingo Ch Singles Q": "Santo Domingo",
    "Santo Domingo Ch Singles": "Santo Domingo",
    "Grodzisk Mazowiecki Ch Singles Q": "Grodzisk Mazowiecki",
    "Grodzisk Mazowiecki Ch Singles": "Grodzisk Mazowiecki",
    "Vancouver WTA Singles": "Vancouver",
    "Cincinnati WTA Singles": "Cincinnati",
    "Canada TMS Singles Q": "Canada",
    "Canada TMS Singles": "Canada",
    "San Marino Ch Singles Q": "San Marino",
    "Chicago Ch Singles": "Chicago",
    "Meerbusch Ch Singles": "Meerbusch",
    "Concord WTA Singles": "Concord",
    "Canada WTA Singles": "Canada",
    "Washington ATP Singles Q": "Washington",
    "Washington ATP Singles": "Washington",
    "Los Cabos ATP Singles": "Los Cabos",
    "Lexington Ch Singles Q": "Lexington",
    "Lexington Ch Singles": "Lexington",
    "Cordenons Ch Singles": "Cordenons",
    "Liberec Ch Singles Q": "Liberec",
    "Liberec Ch Singles": "Liberec",
    "Iasi WTA Singles": "Iasi",
    "Washington WTA Singles": "Washington",
    "Atlanta ATP Singles Q": "Atlanta",
    "Atlanta ATP Singles": "Atlanta",
    "Kitzbuhel ATP Singles": "Kitzbuhel",
    "Umag ATP Singles": "Umag",
    "Zug Ch Singles": "Zug",
    "Segovia Ch Singles Q": "Segovia",
    "Winnipeg Ch Singles": "Winnipeg",
    "San Benedetto Del Tronto Ch Singles Q": "San Benedetto Del Tronto",
    "San Benedetto Del Tronto Ch Singles": "San Benedetto Del Tronto",
    "Prague WTA Singles": "Prague",
    "Warsaw WTA Singles Q": "Warsaw",
    "Warsaw WTA Singles": "Warsaw",
    "Hamburg ATP Singles": "Hamburg",
    "Gstaad ATP Singles": "Gstaad",
    "Trieste Ch Singles": "Trieste",
    "Nur-Sultan Ch Singles": "Nur-Sultan",
    "Indianapolis Ch Singles": "Indianapolis",
    "Tampere Ch Singles": "Tampere",
    "Hamburg WTA Singles": "Hamburg",
    "Palermo WTA Singles": "Palermo",
    "Newport ATP Singles": "Newport",
    "Bastad ATP Singles": "Bastad",
    "Iasi Ch Singles Q": "Iasi",
    "Iasi Ch Singles": "Iasi"
}

surface = {
    "Rio de Janeiro ATP Singles": "Clay",
    "Doha ATP Singles": "Hard",
    "Marseille ATP Singles": "Hard",
    "Monterrey Ch Singles": "Hard",
    "Bengaluru Ch Singles": "Hard",
    "Rome GA Ch Singles Q": "Clay",
    "Rome GA Ch Singles": "Clay",
    "Rovereto Ch Singles Q": "Hard",
    "Rovereto Ch Singles": "Hard",
    "Dubai WTA Singles": "Hard",
    "Merida WTA Singles": "Hard",
    "Rotterdam ATP Singles": "Hard",
    "Delray Beach ATP Singles Q": "Hard",
    "Delray Beach ATP Singles": "Hard",
    "Manama Ch Singles": "Hard",
    "Chennai Ch Singles Q": "Hard",
    "Chennai Ch Singles": "Hard",
    "Cherbourg Ch Singles Q": "Hard",
    "Doha WTA Singles": "Hard",
    "Doha WTA Singles Q": "Hard",
    "Dallas ATP Singles Q": "Hard",
    "Dallas ATP Singles": "Hard",
    "Cordoba ATP Singles Q": "Clay",
    "Cordoba ATP Singles": "Clay",
    "Montpellier ATP Singles Q": "Hard",
    "Montpellier ATP Singles": "Hard",
    "Vilnius Ch Singles": "Hard",
    "Tenerife Ch Singles Q": "Hard",
    "Tenerife Ch Singles": "Hard",
    "Abu Dhabi WTA Singles Q": "Hard",
    "Abu Dhabi WTA Singles": "Hard",
    "Linz WTA Singles": "Hard",
    "Koblenz Ch Singles Q": "Hard",
    "Koblenz Ch Singles": "Hard",
    "Burnie Ch Singles Q": "Hard",
    "Cleveland Ch Singles Q": "Hard",
    "Lyon WTA Singles": "Hard",
    "Hua Hin WTA Singles Q": "Hard",
    "Hua Hin WTA Singles": "Hard",
    "Concepcion Ch Singles": "Clay",
    "Ottignies-Louvain-La-Neuve Ch Singles Q": "Hard",
    "Quimper Ch Singles Q": "Hard",
    "Quimper Ch Singles": "Hard",
    "Piracicaba Ch Singles Q": "Clay",
    "Piracicaba Ch Singles": "Clay",
    "Nonthaburi 3 Ch Singles Q": "Hard",
    "Nonthaburi 3 Ch Singles": "Hard",
    "Auckland ATP Singles": "Hard",
    "Adelaide ATP Singles Q": "Hard",
    "Adelaide ATP Singles": "Hard",
    "Adelaide WTA Singles": "Hard",
    "Hobart WTA Singles Q": "Hard",
    "Hobart WTA Singles": "Hard",
    "Nonthaburi 2 Singles Q": "Hard",
    "Oeiras 2 Ch Singles": "Clay",
    "Tigre 2 Ch Singles Q": "Clay",
    "Tigre 2 Ch Singles": "Clay",
    "Pune ATP Singles Q": "Hard",
    "Pune ATP Singles": "Hard",
    "Adelaide WTA Singles Q": "Hard",
    "Auckland WTA Singles": "Hard",
    "Auckland WTA Singles Q": "Hard",
    "Noumea Ch Singles": "Hard",
    "Tigre 1 Ch Singles Q": "Clay",
    "Tigre 1 Ch Singles": "Clay",
    "Oeiras 1 Ch Singles": "Clay",
    "Roanne Ch Singles": "Hard",
    "Bratislava Ch Singles": "Hard",
    "Knoxville Ch Singles Q": "Hard",
    "Matsuyama Ch Singles Q": "Hard",
    "Matsuyama Ch Singles": "Hard",
    "Montevideo Ch Singles": "Clay",
    "Paris TMS Singles": "Hard",
    "Guayaquil Ch Singles Q": "Clay",
    "Guayaquil Ch Singles": "Clay",
    "Sydney Ch Singles": "Hard",
    "Yokohama Ch Singles Q": "Hard",
    "Yokohama Ch Singles": "Hard",
    "Bergamo Ch Singles Q": "Hard",
    "Bergamo Ch Singles": "Hard",
    "Midland WTA Singles": "Hard",
    "Vienna ATP Singles": "Hard",
    "Basel ATP Singles": "Hard",
    "Brest Ch Singles": "Hard",
    "Playford Ch Singles Q": "Hard",
    "Las Vegas Ch Singles Q": "Hard",
    "Las Vegas Ch Singles": "Hard",
    "Lima Ch Singles Q": "Clay",
    "Lima Ch Singles": "Clay",
    "Ortisei Ch Singles Q": "Hard",
    "Ortisei Ch Singles": "Hard",
    "Tampico WTA Singles Q": "Hard",
    "Antwerp ATP Singles Q": "Hard",
    "Antwerp ATP Singles": "Hard",
    "Stockholm ATP Singles Q": "Hard",
    "Busan Ch Singles Q": "Hard",
    "Busan Ch Singles": "Hard",
    "Hamburg Ch Singles": "Clay",
    "Naples ATP Singles Q": "Hard",
    "Naples ATP Singles": "Hard",
    "Guadalajara WTA Singles": "Hard",
    "Rouen WTA Singles": "Hard",
    "Gijon ATP Singles": "Hard",
    "Gijon ATP Singles Q": "Hard",
    "Florence ATP Singles": "Hard",
    "Seoul Ch Singles": "Hard",
    "St. Tropez Ch Singles Q": "Hard",
    "St. Tropez Ch Singles": "Hard",
    "Ismaning Ch Singles": "Hard",
    "San Diego WTA Singles": "Hard",
    "San Diego WTA Singles Q": "Hard",
    "Cluj-Napoca WTA Singles Q": "Hard",
    "Cluj-Napoca WTA Singles": "Hard",
    "Astana ATP Singles": "Hard",
    "Tokyo ATP Singles": "Hard",
    "Parma Ch Singles": "Clay",
    "Mouilleron Le Captif Ch Singles": "Hard",
    "Campinas Ch Singles": "Clay",
    "Campinas Ch Singles Q": "Clay",
    "Gwangju Ch Singles": "Hard",
    "Gwangju Ch Singles Q": "Hard",
    "Tiburon Ch Singles": "Hard",
    "Alicante Ch Singles Q": "Hard",
    "Alicante Ch Singles": "Hard",
    "Monastir WTA Singles Q": "Hard",
    "Monastir WTA Singles": "Hard",
    "Ostrava WTA Singles Q": "Hard",
    "Ostrava WTA Singles": "Hard",
    "Seoul ATP Singles": "Hard",
    "Tel Aviv ATP Singles": "Hard",
    "Sofia ATP Singles": "Hard",
    "Sofia ATP Singles Q": "Hard",
    "Orleans Ch Singles": "Hard",
    "Lisbon Ch Singles Q": "Clay",
    "Lisbon Ch Singles": "Clay",
    "Buenos Aires Ch Singles Q": "Clay",
    "Buenos Aires Ch Singles": "Clay",
    "Charleston Ch Singles": "Clay",
    "Parma WTA Singles": "Clay",
    "Tallinn WTA Singles": "Hard",
    "Metz ATP Singles": "Hard",
    "San Diego ATP Singles": "Hard",
    "Genoa Ch Singles": "Clay",
    "Braga Ch Singles": "Clay",
    "Braga Ch Singles Q": "Clay",
    "Villa Maria Ch Singles": "Clay",
    "Sibiu Ch Singles": "Clay",
    "Columbus Ch Singles": "Hard",
    "Tokyo WTA Singles": "Hard",
    "Budapest WTA Singles": "Hard",
    "Szczecin Ch Singles Q": "Clay",
    "Cary Ch Singles": "Hard",
    "Istanbul Ch Singles": "Hard",
    "Bucharest WTA Singles": "Clay",
    "Portoroz WTA Singles": "Hard",
    "Tulln Ch Singles": "Clay",
    "Seville Ch Singles": "Clay",
    "Cassis Ch Singles Q": "Hard",
    "Nonthaburi Ch Singles Q": "Hard",
    "Nonthaburi Ch Singles": "Hard",
    "Como Ch Singles Q": "Clay",
    "Como Ch Singles": "Clay",
    "Toulouse Ch Singles Q": "Hard",
    "Toulouse Ch Singles": "Hard",
    "Mallorca Ch Singles Q": "Hard",
    "Mallorca Ch Singles": "Hard",
    "Winston-Salem ATP Singles": "Hard",
    "Banja Luka Ch Singles Q": "Clay",
    "Banja Luka Ch Singles": "Clay",
    "Prague Ch Singles Q": "Clay",
    "Prague Ch Singles": "Clay",
    "Cleveland WTA Singles": "Hard",
    "Granby WTA Singles Q": "Hard",
    "Granby WTA Singles": "Hard",
    "Cincinnati TMS Singles Q": "Hard",
    "Cincinnati TMS Singles": "Hard",
    "Vancouver Ch Singles Q": "Hard",
    "Vancouver Ch Singles": "Hard",
    "Santo Domingo Ch Singles Q": "Clay",
    "Santo Domingo Ch Singles": "Clay",
    "Grodzisk Mazowiecki Ch Singles Q": "Hard",
    "Grodzisk Mazowiecki Ch Singles": "Hard",
    "Vancouver WTA Singles": "Hard",
    "Cincinnati WTA Singles": "Hard",
    "Canada TMS Singles Q": "Hard",
    "Canada TMS Singles": "Hard",
    "San Marino Ch Singles Q": "Clay",
    "Chicago Ch Singles": "Hard",
    "Meerbusch Ch Singles": "Clay",
    "Concord WTA Singles": "Hard",
    "Canada WTA Singles": "Hard",
    "Washington ATP Singles Q": "Hard",
    "Washington ATP Singles": "Hard",
    "Los Cabos ATP Singles": "Hard",
    "Lexington Ch Singles Q": "Hard",
    "Lexington Ch Singles": "Hard",
    "Cordenons Ch Singles": "Clay",
    "Liberec Ch Singles Q": "Clay",
    "Liberec Ch Singles": "Clay",
    "Iasi WTA Singles": "Clay",
    "Washington WTA Singles": "Hard",
    "Atlanta ATP Singles Q": "Hard",
    "Atlanta ATP Singles": "Hard",
    "Kitzbuhel ATP Singles": "Clay",
    "Umag ATP Singles": "Clay",
    "Zug Ch Singles": "Clay",
    "Segovia Ch Singles Q": "Hard",
    "Winnipeg Ch Singles": "Hard",
    "San Benedetto Del Tronto Ch Singles Q": "Clay",
    "San Benedetto Del Tronto Ch Singles": "Clay",
    "Prague WTA Singles": "Clay",
    "Warsaw WTA Singles Q": "Clay",
    "Warsaw WTA Singles": "Clay",
    "Hamburg ATP Singles": "Clay",
    "Gstaad ATP Singles": "Clay",
    "Trieste Ch Singles": "Clay",
    "Nur-Sultan Ch Singles": "Hard",
    "Indianapolis Ch Singles": "Hard",
    "Tampere Ch Singles": "Clay",
    "Hamburg WTA Singles": "Clay",
    "Palermo WTA Singles": "Clay",
    "Newport ATP Singles": "Grass",
    "Bastad ATP Singles": "Clay",
    "Iasi Ch Singles Q": "Clay",
    "Iasi Ch Singles": "Clay"
}


def injury():

    # create a dictionary to store the relevant data
    data = {"Date": [], "Player": [], "Tournament": [], "Injury": []}

    for row in rows:
        date_and_player, injury_and_tournament = row.split(" - ", 1) # 1 split only
        
        # split to extract injury and tournament, since type of injury is irrelevant
        injury, tournament = injury_and_tournament.split(" from ", 1)

        # Split the date and player details
        date, player = date_and_player.split(" ", 1)

        player, injury = player.split(") ", 1)
        
        # Insert into database, injury = 1 in all cases 
        data["Date"].append(date)
        data["Player"].append(player)
        data["Tournament"].append(tournament)
        data["Injury"].append(1)
        
        
    df = pd.DataFrame(data)

    
    df['Surface'] = df['Tournament'].map(surface)
    df['Location'] = df['Tournament'].map(location)

    df = df.iloc[:, [0, 1, 2, 5, 4, 3]]

    return df

