"""
Program to take in the atp_tennis.csv data and convert it into a db file
"""

import pandas as pd
import sqlite3

location = {
    "Australian Hardcourt Championships": "Adelaide",
    "Gold Flake Open": "Chennai",
    "Qatar Open": "Doha",
    "Heineken Open": "Auckland",
    "Sydney International": "Sydney",
    "Australian Open": "Melbourne",
    "Dubai Open": "Dubai",
    "Marseille Open": "Marseille",
    "Sybase Open": "San Jose",
    "Kroger St. Jude": "Memphis",
    "ABN AMRO World Tennis Tournament": "Rotterdam",
    "AXA Cup": "London",
    "Mexican Open": "Acapulco",
    "Copenhagen Open": "Copenhagen",
    "Citrix Tennis Championships": "Delray Beach",
    "Chevrolet Cup": "Santiago",
    "Colombia Open": "Bogota",
    "Franklin Templeton Tennis Classic": "Scottsdale",
    "Indian Wells TMS": "Indian Wells",
    "Ericsson Open": "Miami",
    "Galleryfurniture.com Tennis Challenge": "Houston",
    "Grand Prix Hassan II": "Casablanca",
    "Estoril Open": "Estoril",
    "Monte Carlo Masters": "Monte Carlo",
    "Open Seat Godo": "Barcelona",
    "Mallorca Open": "Mallorca",
    "BMW Open": "Munich",
    "U.S. Clay Court Championships": "Houston",
    "Rome TMS": "Rome",
    "Hamburg TMS": "Hamburg",
    "Internationaler Raiffeisen Grand Prix": "St. Pölten",
    "French Open": "Paris",
    "Gerry Weber Open": "Halle",
    "Stella Artois": "London",
    "Nottingham Open": "Nottingham",
    "Heineken Trophy": "Hertogenbosch",
    "Wimbledon": "London",
    "Swedish Open": "Båstad",
    "Gstaad Open": "Gstaad",
    "Hall of Fame Championships": "Newport",
    "Dutch Open": "Amsterdam",
    "Mercedes Cup": "Stuttgart",
    "Croatia Open": "Umag",
    "Generali Open": "Kitzbühel",
    "Mercedes-Benz Cup": "Los Angeles",
    "Tennis Int'l of San Marino": "San Marino",
    "Toronto TMS": "Toronto",
    "Cincinnati TMS": "Cincinnati",
    "RCA Championships": "Indianapolis",
    "Legg Mason Classic": "Washington",
    "The Hamlet Cup": "Long Island",
    "US Open": "New York",
    "Open Romania": "Bucharest",
    "President's Cup": "Tashkent",
    "Campionati Internazionali Di Sicilia": "Palermo",
    "Salem Open": "Hong Kong",
    "Japan Open": "Tokyo",
    "CA Tennis Trophy": "Vienna",
    "Heineken Open Shanghai": "Shanghai",
    "adidas Open": "Hamburg",
    "Swiss Indoors": "Basel",
    "Kremlin Cup": "Moscow",
    "Stuttgart TMS": "Stuttgart",
    "Grand Prix de Lyon": "Lyon",
    "St. Petersburg Open": "St. Petersburg",
    "BNP Paribas": "Paris",
    "Samsung Open": "Seoul",
    "Stockholm Open": "Stockholm",
    "Masters Cup": "Shanghai",
    "AAPT Championships": "Adelaide",
    "TATA Open": "Chennai",
    "adidas International": "Sydney",
    "Milan Indoors": "Milan",
    "Bellsouth Open": "Vina del Mar",
    "Copa AT&T": "Buenos Aires",
    "Abierto Mexicano": "Acapulco",
    "Dubai Championships": "Dubai",
    "Verizon Tennis Challenge": "Atlanta",
    "U.S. Men's Clay Court Championships": "Houston",
    "Idea Prokom Open": "Sopot",
    "Montreal TMS": "Montreal",
    "Hamlet Cup": "Long Island",
    "Gelsor Open": "Bucharest",
    "Brasil Open": "Costa do Sauipe",
    "Pacific Life Open": "Indian Wells",
    "NASDAQ-100 Open": "Miami",
    "Queens Club": "London",
    "Ordina Open": "Hertogenbosch",
    "Energis Open": "Amsterdam",
    "TD Waterhouse Cup": "Long Island",
    "Madrid Masters": "Madrid",
    "Qatar Exxon Mobil Open": "Doha",
    "Breil ATP": "Milan",
    "Open 13": "Marseille",
    "Siebel Open": "San Jose",
    "International Championships": "Casablanca",
    "CAM Open Comunidad Valenciana": "Valencia",
    "Telecom Italia Masters Roma": "Rome",
    "Allianz Suisse Open": "Gstaad",
    "Priority Telecom Dutch Open": "Amsterdam",
    "Western & Southern Financial Group Masters": "Cincinnati",
    "Thailand Open": "Bangkok",
    "Open de Moselle": "Metz",
    "Indesit ATP Milano Indoor": "Milan",
    "ATP Buenos Aires 2004": "Buenos Aires",
    "China Open": "Beijing",
    "Next Generation Hardcourts": "Adelaide",
    "Medibank International": "Sydney",
    "Internazionali di Lombardia": "Milan",
    "ATP Buenos Aires 2005": "Buenos Aires",
    "SAP Open": "San Jose",
    "Regions Morgan Keegan Championships": "Memphis",
    "Dubai Duty Free Men's Open": "Dubai",
    "Channel Open": "Las Vegas",
    "Open de Tenis Comunidad Valenciana": "Valencia",
    "Rogers Cup": "Montreal",
    "Pilot Pen Tennis": "New Haven",
    "Vietnam Open": "Ho Chi Minh City",
    "BA-CA Tennis Trophy": "Vienna",
    "Davidoff Swiss Indoors": "Basel",
    "Next Generation Adelaide International": "Adelaide",
    "Chennai Open": "Chennai",
    "Movistar Open": "Vina del Mar",
    "PBZ Zagreb Indoors": "Zagreb",
    "Copa Telmex": "Buenos Aires",
    "Dubai Tennis Championships": "Dubai",
    "Campionati Internazional d'Italia": "Rome",
    "Hypo Group Tennis International": "Poertschach",
    "Red Letter Days Open": "Nottingham",
    "Synsam Swedish Open": "Båstad",
    "Countrywide Classic": "Los Angeles",
    "Rogers Masters": "Montreal",
    "Kingfisher Airlines Tennis Open": "Mumbai",
    "Sony Ericsson Open": "Miami",
    "Internazionali BNL d'Italia": "Rome",
    "The Nottingham Open": "Nottingham",
    "Catella Swedish Open": "Båstad",
    "Indianapolis Tennis Championships": "Indianapolis",
    "Austrian Open": "Kitzbühel",
    "AIG Japan Open Tennis Championships": "Tokyo",
    "Open Sabadell Atlántico 2008": "Barcelona",
    "Orange Prokom Open": "Sopot",
    "Slazenger Open": "Nottingham",
    "Studena Croatia Open": "Umag",
    "Brisbane International": "Brisbane",
    "SA Tennis Open": "Johannesburg",
    "BNP Paribas Open": "Indian Wells",
    "Open Banco Sabadell": "Barcelona",
    "Serbia Open": "Belgrade",
    "Mutua Madrileña Madrid Open": "Madrid",
    "AEGON Championships": "London",
    "AEGON International": "Eastbourne",
    "International German Open": "Hamburg",
    "LA Tennis Open": "Los Angeles",
    "Proton Malaysian Open": "Kuala Lumpur",
    "Rakuten Japan Open Tennis Championships": "Tokyo",
    "Shanghai Masters": "Shanghai",
    "Valencia Open 500": "Valencia",
    "BNP Paribas Masters": "Paris",
    "Open de Nice Côte d’Azur": "Nice",
    "Unicef Open": "Hertogenbosch",
    "SkiStar Swedish Open": "Båstad",
    "Atlanta Tennis Championships": "Atlanta",
    "German Open Tennis Championships": "Hamburg",
    "Farmers Classic": "Los Angeles",
    "Open Sud de France": "Montpellier",
    "Copa Claro": "Buenos Aires",
    "Bet-At-Home Cup": "Kitzbühel",
    "Winston-Salem Open at Wake Forest University": "Winston-Salem",
    "Malaysian Open": "Kuala Lumpur",
    "Erste Bank Open": "Vienna",
    "Apia International": "Sydney",
    "VTR Open": "Vina del Mar",
    "BRD Nastase Tiriac Trophy": "Bucharest",
    "Mutua Madrid Open": "Madrid",
    "ATP Vegeta Croatia Open": "Umag",
    "BB&T Atlanta Open": "Atlanta",
    "Crédit Agricole Suisse Open Gstaad": "Gstaad",
    "Citi Open": "Washington",
    "U.S. National Indoor Tennis Championships": "Memphis",
    "Portugal Open": "Oeiras",
    "Power Horse Cup": "Dusseldorf",
    "Topshelf Open": "Hertogenbosch",
    "Claro Open Colombia": "Bogotá",
    "Royal Guard Open Chile": "Santiago",
    "Delray Beach Open": "Delray Beach",
    "Rio Open": "Rio de Janeiro",
    "Dusseldorf Open": "Dusseldorf",
    "Shenzhen Open": "Shenzhen",
    "Ecuador Open": "Quito",
    "Memphis Open": "Memphis",
    "Argentina Open": "Buenos Aires",
    "Millenium Estoril Open": "Estoril",
    "Istanbul Open": "Istanbul",
    "Geneva Open": "Geneva",
    "AEGON Open": "Nottingham",
    "Konzum Croatia Open": "Umag",
    "Suisse Open Gstaad": "Gstaad",
    "ASB Classic": "Auckland",
    "Garanti Koza Sofia Open": "Sofia",
    "German Tennis Championships": "Hamburg",
    "Abierto Mexicano Mifel": "Los Cabos",
    "Chengdu Open": "Chengdu",
    "European Open": "Antwerp",
    "Gazprom Hungarian Open": "Budapest",
    "Lyon Open": "Lyon",
    "Ricoh Open": "Hertogenbosch",
    "Antalya Open": "Antalya",
    "Tata Open": "Pune",
    "New York Open": "New York",
    "Eastbourne International": "Eastbourne",
    "Maharashtra Open": "Pune",
    "Cordoba Open": "Cordoba",
    "Sofia Open": "Sofia",
    "Hungarian Open": "Budapest",
    "Rosmalen Grass Court Championships": "Hertogenbosch",
    "Halle Open": "Halle",
    "Queen's Club Championships": "London",
    "Zhuhai Open": "Zhuhai",
    "Adelaide International": "Adelaide",
    "Chile Open": "Santiago",
    "bett1HULKS Indoors": "Cologne",
    "Forte Village Sardegna Open": "Sardinia",
    "bett1HULKS Championship": "Cologne",
    "Astana Open": "Nur-Sultan",
    "Great Ocean Road Open": "Melbourne",
    "Murray River Open": "Melbourne",
    "Singapore Open": "Singapore",
    "Sardegna Open": "Sardinia",
    "AnyTech365 Andalucia Open": "Marbella",
    "Barcelona Open": "Barcelona",
    "Belgrade Open": "Belgrade",
    "Emilia-Romagna Open": "Parma",
    "Viking International": "Eastbourne",
    "Mallorca Championships": "Mallorca",
    "Nordea Open": "Båstad",
    "Mifel Open": "Los Cabos",
    "Canadian Open": "Toronto",
    "San Diego Open": "San Diego",
    "Vienna Open": "Vienna",
    "Adelaide International 1": "Adelaide",
    "Melbourne Summer Set": "Melbourne",
    "Adelaide International 2": "Adelaide",
    "Sydney Tennis Classic": "Sydney",
    "Dallas Open": "Dallas",
    "Atlanta Open": "Atlanta",
    "Los Cabos Open": "Los Cabos",
    "Korea Open": "Seoul",
    "Tel Aviv Open": "Tel Aviv",
    "Firenze Open": "Florence",
    "Gijon Open": "Gijon",
    "Napoli Cup": "Naples",
    "Srpska Open": "Banja Luka",
    "Stuttgart Open": "Stuttgart",
    "Zhuhai Championships": "Zhuhai",
    "Nordic Open": "Stockholm",
    "Japan Open Tennis Championships": "Tokyo",
    "Hong Kong Tennis Open": "Hong Kong",
    "Tiriac Open": "Bucharest"
}

def tennis():
    # Load the CSV file into a DataFrame
    csv_file = 'atp_tennis.csv'

    df1 = pd.read_csv(csv_file)
    df1.drop(columns=["Player_2", "Court", "Round", "Series", "Rank_1", "Rank_2", "Pts_1", "Pts_2", "Odd_1", "Odd_2", "Score", "Winner", "Best of"], inplace=True)
    df1.rename(columns={"Player_1": "Player"}, inplace=True)

    df2 = pd.read_csv(csv_file)
    df2.drop(columns=["Player_1", "Court", "Round", "Series", "Rank_1", "Rank_2", "Pts_1", "Pts_2", "Odd_1", "Odd_2", "Score", "Winner", "Best of"], inplace=True)
    df2.rename(columns={"Player_2": "Player"}, inplace=True)

    frames = [df1, df2]

    df = pd.concat(frames)
    df = df.iloc[:,[1, 0, 3, 2]]
    df = df.iloc[:,[0, 2, 1, 3]]
    df['Location'] = df['Tournament'].map(location)
    df = df.iloc[:, [0, 1, 2, 4, 3]]
    df.insert(5, "Injury", 0, True)

    # # Connect to the SQLite database (it will be created if it doesn't exist)
    # conn = sqlite3.connect(db_name)
    # cursor = conn.cursor()

    # # Write the DataFrame to a SQL table
    # df.to_sql(table_name, conn, if_exists='replace', index=False)

    # # Commit and close the connection
    # conn.commit()
    # conn.close()

    # print(f"CSV data has been successfully inserted into the {table_name} table in {db_name} database.")
    # print(df)
    return df

tennis()


